# from character.character_data.stats.presets.rocker import rocker_presets
# from character.character_data.stats.presets.fixer import fixer_presets
from random import choice

# from .presets.rocker import rocker_presets
# from .presets.fixer import fixer_presets

# STATS_PRESETS = {
#     # 'ROCKER': rocker_presets,
#     # 'FIXER': fixer_presets,
#     1: rocker_presets,
#     2: fixer_presets
# }

STATS_PRESETS = {
    'ROCKER': {
        1: {
            "intelligence": 5,
            "reflexes": 8,
            "agility": 5,
            "tech": 4,
            "cool": 9,
            "will": 8,
            "luck": 6,
            "movement": 6,
            "body": 10,
            "empathy": 6,
        },
        2: {
            "intelligence": 5,
            "reflexes": 10,
            "agility": 6,
            "tech": 3,
            "cool": 9,
            "will": 10,
            "luck": 6,
            "movement": 6,
            "body": 10,
            "empathy": 4,
        },
        3: {
            "intelligence": 6,
            "reflexes": 10,
            "agility": 5,
            "tech": 3,
            "cool": 9,
            "will": 10,
            "luck": 7,
            "movement": 5,
            "body": 8,
            "empathy": 5,
        },
        4: {
            "intelligence": 6,
            "reflexes": 9,
            "agility": 5,
            "tech": 6,
            "cool": 9,
            "will": 9,
            "luck": 5,
            "movement": 6,
            "body": 8,
            "empathy": 4,
        },
        5: {
            "intelligence": 5,
            "reflexes": 10,
            "agility": 6,
            "tech": 3,
            "cool": 10,
            "will": 10,
            "luck": 6,
            "movement": 6,
            "body": 8,
            "empathy": 4,
        },
        6: {
            "intelligence": 6,
            "reflexes": 10,
            "agility": 7,
            "tech": 4,
            "cool": 8,
            "will": 10,
            "luck": 5,
            "movement": 7,
            "body": 9,
            "empathy": 5,
        }},
    'FIXER': {
        1: {
            "intelligence": 7,
            "reflexes": 6,
            "agility": 6,
            "tech": 3,
            "cool": 6,
            "will": 6,
            "luck": 7,
            "movement": 5,
            "body": 6,
            "empathy": 10,
        },
        2: {
            "intelligence": 9,
            "reflexes": 5,
            "agility": 5,
            "tech": 5,
            "cool": 6,
            "will": 6,
            "luck": 10,
            "movement": 5,
            "body": 5,
            "empathy": 10,
        },
        3: {
            "intelligence": 7,
            "reflexes": 5,
            "agility": 5,
            "tech": 5,
            "cool": 6,
            "will": 6,
            "luck": 10,
            "movement": 5,
            "body": 5,
            "empathy": 9,
        },
        4: {
            "intelligence": 7,
            "reflexes": 6,
            "agility": 7,
            "tech": 7,
            "cool": 7,
            "will": 7,
            "luck": 7,
            "movement": 7,
            "body": 6,
            "empathy": 9,
        },
        5: {
            "intelligence": 10,
            "reflexes": 5,
            "agility": 5,
            "tech": 5,
            "cool": 5,
            "will": 5,
            "luck": 10,
            "movement": 6,
            "body": 5,
            "empathy": 9,
        },
        6: {
            "intelligence": 9,
            "reflexes": 5,
            "agility": 5,
            "tech": 5,
            "cool": 7,
            "will": 7,
            "luck": 10,
            "movement": 7,
            "body": 5,
            "empathy": 9,
        },
    }}


if __name__ == '__main__':
    print(STATS_PRESETS['FIXER'][choice(list(STATS_PRESETS["FIXER"]))])
