# Generated by Django 4.0 on 2022-08-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Punk', max_length=64, verbose_name='name')),
                ('role', models.IntegerField(choices=[(1, 'FIXER'), (2, 'ROCKERBOY'), (3, 'SOLO'), (4, 'NETRUNNER'), (5, 'NOMAD'), (6, 'TECH'), (7, 'COP'), (8, 'CORPORATE'), (9, 'MEDIC'), (10, 'JOUNALIST')], verbose_name='role')),
                ('hit_points', models.CharField(max_length=64, verbose_name='hit_points')),
                ('max_hit_points', models.CharField(max_length=64, verbose_name='max_hit_points')),
                ('left_hand_weapon', models.CharField(max_length=64, verbose_name='left_hand_weapon')),
                ('right_hand_weapon', models.CharField(max_length=64, verbose_name='right_hand_weapon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intel', models.IntegerField(default=5, verbose_name='intel')),
                ('ref', models.IntegerField(default=5, verbose_name='ref')),
                ('dex', models.IntegerField(default=5, verbose_name='dex')),
                ('tech', models.IntegerField(default=5, verbose_name='tech')),
                ('cool', models.IntegerField(default=5, verbose_name='cool')),
                ('will', models.IntegerField(default=5, verbose_name='will')),
                ('lusk', models.IntegerField(default=5, verbose_name='lusk')),
                ('move', models.IntegerField(default=5, verbose_name='move')),
                ('body', models.IntegerField(default=5, verbose_name='body')),
                ('emp', models.IntegerField(default=5, verbose_name='emp')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character', verbose_name='character')),
            ],
            options={
                'verbose_name': 'Статы',
                'verbose_name_plural': 'Статы',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brawling', models.IntegerField(default=5, verbose_name='brawling')),
                ('evasion', models.IntegerField(default=5, verbose_name='evasion')),
                ('marksmanship', models.IntegerField(default=5, verbose_name='marksmanship')),
                ('melee_weapon', models.IntegerField(default=5, verbose_name='melee_weapon')),
                ('concentration', models.IntegerField(default=5, verbose_name='concentration')),
                ('perception', models.IntegerField(default=5, verbose_name='perception')),
                ('tracking', models.IntegerField(default=5, verbose_name='tracking')),
                ('driving', models.IntegerField(default=5, verbose_name='driving')),
                ('athletics', models.IntegerField(default=5, verbose_name='athletics')),
                ('stealth', models.IntegerField(default=5, verbose_name='stealth')),
                ('basic_tech', models.IntegerField(default=5, verbose_name='basic_tech')),
                ('cybertech', models.IntegerField(default=5, verbose_name='cybertech')),
                ('first_aid', models.IntegerField(default=5, verbose_name='first_aid')),
                ('play_instrument', models.IntegerField(default=5, verbose_name='play_instrument')),
                ('education', models.IntegerField(default=5, verbose_name='education')),
                ('local_expert', models.IntegerField(default=5, verbose_name='local_expert')),
                ('bribery', models.IntegerField(default=5, verbose_name='bribery')),
                ('conversation', models.IntegerField(default=5, verbose_name='conversation')),
                ('human_perception', models.IntegerField(default=5, verbose_name='human_perception')),
                ('interrogation', models.IntegerField(default=5, verbose_name='interrogation')),
                ('persuasion', models.IntegerField(default=5, verbose_name='persuasion')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character', verbose_name='character')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='LifePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=2048, verbose_name='family')),
                ('motivation', models.CharField(max_length=2048, verbose_name='motivation')),
                ('goals', models.CharField(max_length=2048, verbose_name='goals')),
                ('friends', models.CharField(max_length=2048, verbose_name='friends')),
                ('enemies', models.CharField(max_length=2048, verbose_name='enemies')),
                ('romance', models.CharField(max_length=2048, verbose_name='romance')),
                ('personality', models.CharField(max_length=2048, verbose_name='personality')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character', verbose_name='character')),
            ],
            options={
                'verbose_name': 'Жизненный путь',
                'verbose_name_plural': 'Жизненные пути',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('item_type', models.IntegerField(choices=[(0, 'subject'), (1, 'melee_weapon'), (2, 'gun'), (3, 'disposable_weapon'), (4, 'implanted_weapon'), (5, 'modifier_implants'), (6, 'loot_implants'), (7, 'pharmaceuticals'), (8, 'electronics'), (9, 'coins')], verbose_name='item_type')),
                ('weight', models.IntegerField(choices=[(0, 'implant'), (1, 'light'), (2, 'medium'), (3, 'heavy')], verbose_name='mass')),
                ('price', models.IntegerField(default=50, verbose_name='intel')),
                ('installed', models.BooleanField(default=False)),
                ('slot', models.CharField(choices=[('brain', 'brain'), ('left_eye', 'left_eye'), ('right_eye', 'right_eye'), ('hearing', 'hearing'), ('leather', 'leather'), ('heart', 'heart'), ('left_hand', 'left_hand'), ('right_hand', 'right_hand'), ('left_leg', 'left_leg'), ('right_leg', 'right_leg')], max_length=64, null=True, verbose_name='mass')),
                ('humanity_penalty', models.CharField(max_length=64, null=True, verbose_name='hit_points')),
                ('skill_modifier', models.CharField(max_length=64, null=True, verbose_name='hit_points')),
                ('hands', models.IntegerField(choices=[(0, 'implant'), (1, 'one'), (2, 'Two')], null=True, verbose_name='hands')),
                ('is_hidden', models.BooleanField(default=False, null=True)),
                ('dices', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='dises')),
                ('dice_type', models.IntegerField(choices=[(0, 'd6'), (1, 'd10')], null=True, verbose_name='dises_type')),
                ('ammo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)], null=True, verbose_name='ammo')),
                ('max_ammo', models.IntegerField(choices=[], null=True, verbose_name='max_ammo')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character', verbose_name='character')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='ImplantSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brain', to='character.items', verbose_name='brain')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character', verbose_name='character')),
                ('hearing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hearing', to='character.items', verbose_name='hearing')),
                ('heart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Heart', to='character.items', verbose_name='heart')),
                ('leather', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leather', to='character.items', verbose_name='leather')),
                ('left_eye', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeftEye', to='character.items', verbose_name='left_eye')),
                ('left_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeftHand', to='character.items', verbose_name='left_hand')),
                ('left_leg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeftLeg', to='character.items', verbose_name='left_leg')),
                ('right_eye', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RightEye', to='character.items', verbose_name='right_eye')),
                ('right_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RightHand', to='character.items', verbose_name='right_hand')),
                ('right_leg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RightLeg', to='character.items', verbose_name='right_leg')),
            ],
            options={
                'verbose_name': 'Слоты имплантов',
                'verbose_name_plural': 'Слоты имплантов',
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_level', models.IntegerField(default=5, null=True, verbose_name='head_level')),
                ('head_wear', models.IntegerField(default=5, null=True, verbose_name='head_wear')),
                ('body_level', models.IntegerField(default=5, null=True, verbose_name='body_level')),
                ('body_wear', models.IntegerField(default=5, null=True, verbose_name='body_wear')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character', verbose_name='character')),
            ],
            options={
                'verbose_name': 'Броня',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
