# Generated by Django 4.0 on 2022-08-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('FIXER', 'FIXER'), ('ROCKERBOY', 'ROCKERBOY'), ('SOLO', 'SOLO'), ('NETRUNNER', 'NETRUNNER'), ('NOMAD', 'NOMAD'), ('TECH', 'TECH'), ('COP', 'COP'), ('CORPORATE', 'CORPORATE'), ('MEDIC', 'MEDIC'), ('JOUNALIST', 'JOUNALIST')], max_length=16, verbose_name='role'),
        ),
    ]
