# Generated by Django 4.0 on 2022-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(db_index=True, max_length=64, verbose_name='ID')),
                ('intel', models.IntegerField(default=5, verbose_name='intel')),
                ('ref', models.IntegerField(default=5, verbose_name='ref')),
                ('dex', models.IntegerField(default=5, verbose_name='dex')),
                ('tech', models.IntegerField(default=5, verbose_name='tech')),
                ('cool', models.IntegerField(default=5, verbose_name='cool')),
                ('will', models.IntegerField(default=5, verbose_name='will')),
                ('lusk', models.IntegerField(default=5, verbose_name='lusk')),
                ('move', models.IntegerField(default=5, verbose_name='move')),
                ('body', models.IntegerField(default=5, verbose_name='body')),
                ('emp', models.IntegerField(default=5, verbose_name='emp')),
            ],
        ),
    ]
