# Generated by Django 4.0 on 2022-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_path_id', models.CharField(db_index=True, max_length=64, verbose_name='ID')),
                ('family', models.CharField(choices=[(1, 'Ваша семья потеряла всё из-за предательства.'), (2, 'Ваша семья потеряла всё из-за плохой организации.'), (3, 'Вашу семью изгнали или иным способом лишили родного дома/страны/корпорации.'), (4, 'Вся ваша семья в тюрьме, только вы остались на свободе.'), (5, 'Ваша семья исчезла. Вы остались один.'), (6, 'Всю вашу семью убили, вы единственный выжили.'), (7, 'Ваша семья давно участвует в заговоре или вступила в тайную организацию, такую как преступный клан или группа революционеров.'), (8, 'Вашу семью разбросало по миру из-за ударов судьбы.'), (9, 'Ваша семья уже несколько поколений страдает от давней вражды.'), (10, 'Вам достались в наследство семейные долги. Придётся выплатить их, прежде чем вы начнёте жить собственной жизнью.')], max_length=2048, verbose_name='family')),
                ('motivation', models.CharField(choices=[(1, 'Деньги'), (2, 'Честь'), (3, 'Данное вами слово'), (4, 'Честность'), (5, 'Знания'), (6, 'Месть'), (7, 'Любовь'), (8, 'Власть'), (9, 'Удовольствие'), (10, 'Дружба')], max_length=2048, verbose_name='motivation')),
                ('goals', models.CharField(choices=[(1, 'Избавиться от дурной репутации.'), (2, 'Добиться власти и влияния.'), (3, 'Выбраться с Улицы, чего бы это ни стоило.'), (4, 'Причинить боль и страдания всем, кто перешёл вам дорогу.'), (5, 'Избавиться от прошлого и постараться забыть о нём.'), (6, 'Выследить тех, кто испортил вам жизнь, и призвать их к ответу.'), (7, ' Получить то, что принадлежит вам по праву.'), (8, 'По возможности спасти пострадавших членов семьи.'), (9, 'Добиться славы и признания.'), (10, 'Сделать так, чтобы вас боялись и уважали.')], max_length=2048, verbose_name='goals')),
                ('friends', models.CharField(choices=[(1, 'Как старший брат или сестра'), (2, 'Как младший брат или сестра'), (3, 'Учитель или наставник'), (4, 'Партнёр или коллега'), (5, 'Прежняя любовь'), (6, 'Бывший враг'), (7, 'Как отец или мать'), (8, 'Друг детства'), (9, 'Родственник'), (10, 'Человек, разделяющий ваши интересы')], max_length=2048, verbose_name='friends')),
                ('enemies', models.CharField(choices=[(1, 'Бывший друг'), (2, 'Бывший любовник/любовница'), (3, 'Родственник'), (4, 'Враг с детства'), (5, 'Человек, работающий на вас'), (6, 'Человек, на которого вы работаете'), (7, 'Партнёр или коллега'), (8, 'Кто-то из банды бустеров'), (9, 'Менеджер из корпорации'), (10, 'Чиновник из правительства')], max_length=2048, verbose_name='enemies')),
                ('romance', models.CharField(choices=[(1, 'Ваш любимый(ая) погиб от несчастного случая.'), (2, 'Ваш любимый(ая) исчез при загадочных обстоятельствах.'), (3, 'Просто не срослось.'), (4, 'Между вами встали личные интересы или вендетта.'), (5, 'Вашего любимого(ую) похитили.'), (6, 'Ваш любимый(ая) сошёл с ума.'), (7, 'Ваш любимый(ая) покончил с собой.'), (8, 'Ваш любимый(ая) погиб в бою.'), (9, 'Соперник увёл у вас партнёра.'), (10, 'Ваш любимый(ая) в тюрьме или в изгнании.')], max_length=2048, verbose_name='romance')),
                ('personality', models.CharField(choices=[(1, 'Застенчивый и скрытный'), (2, 'Неуживчивый, жестокий, непокорный'), (3, 'Высокомерный, гордый и замкнутый'), (4, 'Непостоянный, безрассудный и упрямый'), (5, 'Придирчивый, капризный и раздражительный'), (6, 'Серьёзный и постоянный'), (7, 'Глуповатый и легкомысленный'), (8, 'Подлый и лживый'), (9, 'Умный и отстранённый'), (10, 'Дружелюбный и общительный')], max_length=2048, verbose_name='personality')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_id', models.CharField(db_index=True, max_length=64, verbose_name='ID')),
                ('brawling', models.IntegerField(default=5, verbose_name='brawling')),
                ('evasion', models.IntegerField(default=5, verbose_name='evasion')),
                ('marksmanship', models.IntegerField(default=5, verbose_name='marksmanship')),
                ('melee_weapon', models.IntegerField(default=5, verbose_name='melee_weapon')),
                ('concentration', models.IntegerField(default=5, verbose_name='concentration')),
                ('perception', models.IntegerField(default=5, verbose_name='perception')),
                ('tracking', models.IntegerField(default=5, verbose_name='tracking')),
                ('driving', models.IntegerField(default=5, verbose_name='driving')),
                ('athletics', models.IntegerField(default=5, verbose_name='athletics')),
                ('stealth', models.IntegerField(default=5, verbose_name='stealth')),
                ('basic_tech', models.IntegerField(default=5, verbose_name='basic_tech')),
                ('cybertech', models.IntegerField(default=5, verbose_name='cybertech')),
                ('first_aid', models.IntegerField(default=5, verbose_name='first_aid')),
                ('play_instrument', models.IntegerField(default=5, verbose_name='play_instrument')),
                ('education', models.IntegerField(default=5, verbose_name='education')),
                ('local_expert', models.IntegerField(default=5, verbose_name='local_expert')),
                ('bribery', models.IntegerField(default=5, verbose_name='bribery')),
                ('conversation', models.IntegerField(default=5, verbose_name='conversation')),
                ('human_perception', models.IntegerField(default=5, verbose_name='human_perception')),
                ('interrogation', models.IntegerField(default=5, verbose_name='interrogation')),
                ('persuasion', models.IntegerField(default=5, verbose_name='persuasion')),
            ],
        ),
    ]
