# Generated by Django 4.0 on 2022-07-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifepath',
            name='life_path_id',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skills_id',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='verbose_name',
        ),
    ]
