# Generated by Django 4.0 on 2022-07-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('character', '0006_remove_lifepath_life_path_id_remove_skills_skills_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Жизненный путь', 'verbose_name_plural': 'Жизненные пути'},
        ),
        migrations.AlterModelOptions(
            name='lifepath',
            options={'verbose_name': 'Жизненный путь', 'verbose_name_plural': 'Жизненные пути'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'Статы', 'verbose_name_plural': 'Статы'},
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='user'),
            preserve_default=False,
        ),
    ]
