# Generated by Django 4.0 on 2022-07-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_alter_lifepath_enemies_alter_lifepath_family_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
    ]
