# Generated by Django 4.0 on 2022-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='Punk', max_length=64, verbose_name='hit_points'),
        ),
    ]
