from core.character_data.items.item_options import ITEM_TYPE, IMPLANT_SLOTS, MASS, HANDS

solo_items = [
    {
        'item_type': ITEM_TYPE['gun'],
        'name': 'Assault Rifle',
        'weight': MASS['heavy'],
        'hands': HANDS['two'],
        'in_hands': True,
        'price': 300,
        'is_hidden': False,
        'dices': 5,
        'dice_type': 6,
        'ammo': 30,
        'max_ammo': 30,
    },
    {
        'item_type': ITEM_TYPE['implanted_weapon'],
        'name': 'Cyberarm',
        'weight': MASS['implant'],
        'installed': True,
        'slot': IMPLANT_SLOTS['right_hand'],
        'price': 500,
        'is_hidden': True,
        'dices': 1,
        'dice_type': 6,
    },
    {
        'item_type': ITEM_TYPE['implanted_weapon'],
        'name': 'Rippers',
        'weight': MASS['implant'],
        'installed': True,
        'slot': IMPLANT_SLOTS['left_hand'],
        'price': 200,
        'is_hidden': True,
        'dices': 2,
        'dice_type': 6,
    },
    {
        'item_type': ITEM_TYPE['modifier_implants'],
        'name': 'Cyberleg Jump Boosters',
        'weight': MASS['implant'],
        'installed': True,
        'slot': IMPLANT_SLOTS['brain'],
        'price': 250,
        'is_hidden': True,
        'dices': 2,
        'dice_type': 6,
    },
    {
        'item_type': ITEM_TYPE['modifier_implants'],
        'name': 'Cyberoptics Targeting',
        'weight': MASS['implant'],
        'installed': True,
        'slot': IMPLANT_SLOTS['right_eye'],
        'price': 350,
        'is_hidden': True,
    },
    {
        'item_type': ITEM_TYPE['electronics'],
        'name': 'Agent',
        'weight': MASS['light'],
        'price': 100,
        'is_hidden': True,
    },

]
